from enum import Enum

class ProblemType(str, Enum):
    FAILED_PAYMENT = "FAILED_PAYMENT"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    OVERDUE_INVOICE = "OVERDUE_INVOICE"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class ActionType(str, Enum):
    RETRY = "RETRY"
    REMIND = "REMIND"
    ESCALATE = "ESCALATE"
    STOP = "STOP"
    VOICE_CALL = "VOICE_CALL"

class PolicyDecision(str, Enum):
    AUTO = "AUTO"
    HUMAN = "HUMAN"
    BLOCK = "BLOCK"
    STOP = "STOP"

class CaseStatus(str, Enum):
    OPEN = "OPEN"
    ANALYZING = "ANALYZING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    SCHEDULED = "SCHEDULED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    STOPPED = "STOPPED"
    REJECTED = "REJECTED"

class TransactionStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    AMBIGUOUS = "AMBIGUOUS"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"

class PaymentState(str, Enum):
    CLEAR = "CLEAR"
    PENDING = "PENDING"
    AMBIGUOUS = "AMBIGUOUS"

class ActorType(str, Enum):
    AI = "AI"
    POLICY = "POLICY"
    HUMAN = "HUMAN"
    SYSTEM = "SYSTEM"
    EXECUTOR = "EXECUTOR"
    VERIFIER = "VERIFIER"

class DiagnosisType(str, Enum):
    TEMPORARY_FAILURE = "TEMPORARY_FAILURE"
    PERMANENT_FAILURE = "PERMANENT_FAILURE"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    INVALID_PAYMENT_DETAILS = "INVALID_PAYMENT_DETAILS"
    FRAUD_RISK = "FRAUD_RISK"
    AMBIGUOUS_STATE = "AMBIGUOUS_STATE"
    CUSTOMER_ACTION_REQUIRED = "CUSTOMER_ACTION_REQUIRED"
    OVERDUE_RECEIVABLE = "OVERDUE_RECEIVABLE"

class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"

class AuditEventType(str, Enum):
    CASE_CREATED = "CASE_CREATED"
    AI_DIAGNOSED = "AI_DIAGNOSED"
    RECOVERY_SCORE_CALCULATED = "RECOVERY_SCORE_CALCULATED"
    ACTION_RECOMMENDED = "ACTION_RECOMMENDED"
    POLICY_APPROVED = "POLICY_APPROVED"
    HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    HUMAN_MODIFIED = "HUMAN_MODIFIED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    PAYMENT_RECHECKED = "PAYMENT_RECHECKED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    REVENUE_RECOVERED = "REVENUE_RECOVERED"
    ACTION_BLOCKED = "ACTION_BLOCKED"
    RECOVERY_STOPPED = "RECOVERY_STOPPED"
    LLM_OUTPUT_INVALID = "LLM_OUTPUT_INVALID"
    VOICE_CALL_REQUESTED = "VOICE_CALL_REQUESTED"
    VOICE_CALL_DISPATCHED = "VOICE_CALL_DISPATCHED"
    VOICE_CALL_COMPLETED = "VOICE_CALL_COMPLETED"
    VOICE_CALL_FAILED = "VOICE_CALL_FAILED"
    P2P_CREATED = "P2P_CREATED"
    P2P_VERIFICATION_STARTED = "P2P_VERIFICATION_STARTED"
    P2P_KEPT = "P2P_KEPT"
    P2P_BROKEN = "P2P_BROKEN"
