import { RecoveryCase, DashboardMetrics } from "./types";

export const INITIAL_METRICS: DashboardMetrics = {
  revenueAtRisk: 5000000, // ₹50.0L
  recoverableRevenue: 4120000, // ₹41.2L
  grossRecovered: 3100000, // ₹31.0L
  incrementalRecovered: 900000, // ₹9.0L
  safetyActionsPrevented: 85,
  decisionDistribution: {
    auto: 420,
    human: 280,
    blocked: 85,
  },
};

export const INITIAL_CASES: RecoveryCase[] = [
  {
    id: "CASE-1021",
    customerName: "Rahul Enterprises",
    customerEmail: "rahul@rahulenterprises.in",
    problem: "Temporary bank/network error",
    amount: 15000,
    score: 87,
    risk: "LOW",
    type: "FAILED_PAYMENT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Temporary bank/network failure during 3DS challenge.",
      recommendation: "Retry once after 30 minutes.",
      score: 87,
      expectedValue: 12900,
      evidence: [
        { id: "e1", text: "8 previous successful payments on merchant account", isPositive: true },
        { id: "e2", text: "Only 1 previous isolated failure in 12 months", isPositive: true },
        { id: "e3", text: "Recent successful payment recorded 48 hours ago", isPositive: true },
        { id: "e4", text: "Retryable bank error code (ERR_NET_TIMEOUT)", isPositive: true },
        { id: "e5", text: "No duplicate charge signal or pending authorization", isPositive: true },
      ],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "All safety and threshold criteria passed.",
      explanation: "Policy approved automatic recovery action without requiring human intervention.",
      rules: [
        { id: "r1", text: "Payment state is clearly failed (No ambiguous debit)", passed: true },
        { id: "r2", text: "Transaction amount (₹15,000) is within auto-approval threshold (₹50,000)", passed: true },
        { id: "r3", text: "Error code is classified as retryable network failure", passed: true },
        { id: "r4", text: "Retry count (0) is below maximum threshold (2)", passed: true },
        { id: "r5", text: "No duplicate charge or dual-processing risk detected", passed: true },
      ],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 30,
    createdAt: "2026-08-28 10:02:00",
    updatedAt: "2026-08-28 10:03:00",
    auditTimeline: [
      {
        id: "a1",
        timestamp: "10:02",
        title: "Payment Failed",
        description: "Transaction ₹15,000 failed with network timeout at gateway.",
        category: "SYSTEM",
      },
      {
        id: "a2",
        timestamp: "10:03",
        title: "Recovery Case Created",
        description: "Case CASE-1021 logged into AI Recovery pipeline.",
        category: "SYSTEM",
      },
      {
        id: "a3",
        timestamp: "10:03",
        title: "AI Diagnosed Temporary Bank Error",
        description: "AI agent evaluated 5 behavioral signals and diagnosed transient network error.",
        category: "AI",
      },
      {
        id: "a4",
        timestamp: "10:03",
        title: "Recovery Score Calculated",
        description: "Calculated recovery score of 87/100 (Expected recovery value: ₹12,900).",
        category: "AI",
      },
      {
        id: "a5",
        timestamp: "10:03",
        title: "Retry Recommended",
        description: "AI recommended single retry after 30-minute cooling window.",
        category: "AI",
      },
      {
        id: "a6",
        timestamp: "10:03",
        title: "Policy Approved Automatic Action",
        description: "Safety Engine confirmed amount ≤ ₹50,000 and zero ambiguity. Auto-approval granted.",
        category: "POLICY",
        badgeText: "AUTO-ALLOWED",
      },
      {
        id: "a7",
        timestamp: "10:03",
        title: "Retry Scheduled",
        description: "Action queued for execution at 10:33 AM.",
        category: "ACTION",
      },
    ],
  },
  {
    id: "CASE-1032",
    customerName: "ABC Ltd",
    customerEmail: "finance@abcltd.com",
    problem: "Bank timeout on large value transfer",
    amount: 75000,
    score: 82,
    risk: "MEDIUM",
    type: "FAILED_PAYMENT",
    paymentState: "BANK_TIMEOUT",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 1,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Inter-bank settlement timeout during peak processing hours.",
      recommendation: "Retry once after 30 minutes.",
      score: 82,
      expectedValue: 61500,
      evidence: [
        { id: "e1", text: "12 previous successful payments on account", isPositive: true },
        { id: "e2", text: "Only 1 previous failure (resolved next day)", isPositive: true },
        { id: "e3", text: "Retryable failure code (BANK_GATEWAY_TIMEOUT)", isPositive: true },
        { id: "e4", text: "No duplicate charge signal detected on bank network", isPositive: true },
      ],
    },
    policyDecision: {
      type: "HUMAN",
      decisionLabel: "HUMAN APPROVAL REQUIRED",
      reason: "Amount (₹75,000) exceeds automatic recovery limit (₹50,000).",
      explanation: "Even though AI confidence is high, policy mandates human verification for transactions above ₹50,000.",
      rules: [
        { id: "r1", text: "Payment state is non-ambiguous", passed: true },
        { id: "r2", text: "Transaction amount exceeds auto threshold (₹75,000 > ₹50,000)", passed: false },
        { id: "r3", text: "Medium risk tier requires merchant sign-off", passed: false },
        { id: "r4", text: "No duplicate charge signal", passed: true },
      ],
    },
    status: "HUMAN_APPROVAL",
    scheduledDelayMinutes: 30,
    createdAt: "2026-08-28 09:45:00",
    updatedAt: "2026-08-28 09:46:00",
    auditTimeline: [
      {
        id: "a1",
        timestamp: "09:45",
        title: "Payment Failed",
        description: "Transaction ₹75,000 timed out at bank server.",
        category: "SYSTEM",
      },
      {
        id: "a2",
        timestamp: "09:46",
        title: "AI Analysis Complete",
        description: "AI calculated score 82/100 and recommended retry after 30m.",
        category: "AI",
      },
      {
        id: "a3",
        timestamp: "09:46",
        title: "Policy Mandated Human Approval",
        description: "Safety Engine flagged amount (₹75,000) exceeding auto limit. Escalated to Approval Queue.",
        category: "POLICY",
        badgeText: "HUMAN APPROVAL REQUIRED",
      },
    ],
  },
  {
    id: "CASE-1048",
    customerName: "XYZ Corp",
    customerEmail: "payments@xyzcorp.org",
    problem: "Ambiguous payment state & potential double debit",
    amount: 25000,
    score: 70,
    risk: "HIGH",
    type: "CHECKOUT",
    paymentState: "AMBIGUOUS",
    possibleDebit: true,
    retryCount: 0,
    maxRetries: 0,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Uncertain gateway callback with pending bank authorization signal.",
      recommendation: "DO NOT RETRY AUTOMATICALLY. Escalate to human manual reconciliation.",
      score: 70,
      expectedValue: 0,
      evidence: [
        { id: "e1", text: "Bank webhook response incomplete (HTTP 502)", isPositive: false },
        { id: "e2", text: "Customer account shows potential pending debit hold", isPositive: false },
        { id: "e3", text: "High risk of duplicate charge if retried immediately", isPositive: false },
      ],
    },
    policyDecision: {
      type: "BLOCK",
      decisionLabel: "BLOCKED — AMBIGUOUS PAYMENT",
      reason: "Payment confirmation is uncertain and customer may already have been debited.",
      explanation: "Retrying an ambiguous transaction risks double-charging the customer and violating merchant compliance rules.",
      rules: [
        { id: "r1", text: "Payment state clarity check", passed: false },
        { id: "r2", text: "Zero duplicate-charge risk check", passed: false },
        { id: "r3", text: "Automatic retry blocked by policy guardrails", passed: false },
      ],
    },
    status: "BLOCKED",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 09:15:00",
    updatedAt: "2026-08-28 09:16:00",
    auditTimeline: [
      {
        id: "a1",
        timestamp: "09:15",
        title: "Payment Ambiguous Signal",
        description: "Gateway response dropped before final status confirmation.",
        category: "SYSTEM",
      },
      {
        id: "a2",
        timestamp: "09:16",
        title: "AI Detected Duplicate Risk",
        description: "AI flagged potential pending customer debit. Recommended NO auto-retry.",
        category: "AI",
      },
      {
        id: "a3",
        timestamp: "09:16",
        title: "Policy Hard-Blocked Retry Action",
        description: "Safety Engine blocked automatic execution. Action prohibited until manual bank reconciliation.",
        category: "POLICY",
        badgeText: "BLOCKED",
      },
    ],
  },
  {
    id: "CASE-1088",
    customerName: "SaaS Dynamics Ltd",
    customerEmail: "billing@saasdynamics.io",
    problem: "Failed recurring subscription mandate",
    amount: 2000,
    score: 91,
    risk: "LOW",
    type: "SUBSCRIPTION",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 3,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Insufficient balance at 2 AM auto-debit attempt.",
      recommendation: "Retry in afternoon window (2:00 PM).",
      score: 91,
      expectedValue: 1820,
      evidence: [
        { id: "e1", text: "24 consecutive successful monthly renewals", isPositive: true },
        { id: "e2", text: "Pay-day pattern detected on 28th of every month", isPositive: true },
        { id: "e3", text: "Clean customer health score", isPositive: true },
      ],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Subscription retry within policy safety limits.",
      explanation: "Automatic smart retry sequence authorized.",
      rules: [
        { id: "r1", text: "Amount ₹2,000 <= auto limit ₹50,000", passed: true },
        { id: "r2", text: "No duplicate risk", passed: true },
      ],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 120,
    createdAt: "2026-08-28 08:30:00",
    updatedAt: "2026-08-28 08:31:00",
    auditTimeline: [
      {
        id: "a1",
        timestamp: "08:30",
        title: "Subscription Mandate Failed",
        description: "Recurring debit of ₹2,000 failed (Insufficient funds).",
        category: "SYSTEM",
      },
      {
        id: "a2",
        timestamp: "08:31",
        title: "AI Optimized Retry Window",
        description: "AI selected optimal afternoon retry window based on historical salary deposit pattern.",
        category: "AI",
      },
      {
        id: "a3",
        timestamp: "08:31",
        title: "Policy Approved",
        description: "Auto-retry authorized.",
        category: "POLICY",
        badgeText: "AUTO-ALLOWED",
      },
    ],
  },
  {
    id: "CASE-1102",
    customerName: "Global Tech Solutions",
    customerEmail: "accounts@globaltech.com",
    problem: "B2B Invoice 18 days overdue",
    amount: 75000,
    score: 78,
    risk: "MEDIUM",
    type: "INVOICE",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 1,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Invoice overdue past standard net-15 terms.",
      recommendation: "Send AI personalized SMS + email payment link with 2-part split offer.",
      score: 78,
      expectedValue: 58500,
      evidence: [
        { id: "e1", text: "High customer credit lifetime value (₹12.5L)", isPositive: true },
        { id: "e2", text: "Past payment pattern shows average 20-day settlement", isPositive: true },
      ],
    },
    policyDecision: {
      type: "HUMAN",
      decisionLabel: "HUMAN APPROVAL REQUIRED",
      reason: "B2B invoice terms alteration requires merchant approval.",
      explanation: "Escalated for merchant account manager sign-off.",
      rules: [
        { id: "r1", text: "High transaction value requires review", passed: false },
      ],
    },
    status: "HUMAN_APPROVAL",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 07:10:00",
    updatedAt: "2026-08-28 07:12:00",
    auditTimeline: [
      {
        id: "a1",
        timestamp: "07:10",
        title: "Invoice Overdue Alert",
        description: "Invoice #INV-9921 past net-15 due date.",
        category: "SYSTEM",
      },
      {
        id: "a2",
        timestamp: "07:12",
        title: "Policy Escalated to Human Approval",
        description: "Human approval requested for split payment outreach.",
        category: "POLICY",
        badgeText: "HUMAN APPROVAL REQUIRED",
      },
    ],
  },
  {
    id: "CASE-1105",
    customerName: "Apex Retail Mart",
    customerEmail: "orders@apexretail.in",
    problem: "UPI Intent App Switch failure",
    amount: 3450,
    score: 89,
    risk: "LOW",
    type: "CHECKOUT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Customer closed UPI app before entering PIN.",
      recommendation: "Send WhatsApp instant collect request.",
      score: 89,
      expectedValue: 3070,
      evidence: [
        { id: "e1", text: "Active checkout session within 15 minutes", isPositive: true },
        { id: "e2", text: "Valid mobile number with WhatsApp integration", isPositive: true },
      ],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Low risk checkout recovery.",
      explanation: "Instant collect trigger approved.",
      rules: [{ id: "r1", text: "Amount within limit", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 5,
    createdAt: "2026-08-28 09:50:00",
    updatedAt: "2026-08-28 09:51:00",
    auditTimeline: [
      { id: "a1", timestamp: "09:50", title: "UPI Abandoned", description: "Customer exited GPay prompt.", category: "SYSTEM" },
      { id: "a2", timestamp: "09:51", title: "Auto Collect Scheduled", description: "WhatsApp collect link queued.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1110",
    customerName: "Vortex Digital",
    customerEmail: "contact@vortexdigital.co",
    problem: "Card expired during recurring cycle",
    amount: 8500,
    score: 85,
    risk: "LOW",
    type: "SUBSCRIPTION",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Card expiry date reached.",
      recommendation: "Trigger Visa/Mastercard Account Updater & notify customer.",
      score: 85,
      expectedValue: 7225,
      evidence: [{ id: "e1", text: "Card updater supported by bank", isPositive: true }],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Standard token update routine.",
      explanation: "Account updater request sent to card network.",
      rules: [{ id: "r1", text: "Compliant token flow", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 60,
    createdAt: "2026-08-28 08:15:00",
    updatedAt: "2026-08-28 08:16:00",
    auditTimeline: [
      { id: "a1", timestamp: "08:15", title: "Card Expired", description: "Renewal failed due to expired card.", category: "SYSTEM" },
      { id: "a2", timestamp: "08:16", title: "Updater Triggered", description: "Network updater request dispatched.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1115",
    customerName: "BlueSky Logistics",
    customerEmail: "ops@blueskylogistics.com",
    problem: "Card limit exceeded",
    amount: 120000,
    score: 65,
    risk: "HIGH",
    type: "FAILED_PAYMENT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 1,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Daily transaction limit exceeded on credit card.",
      recommendation: "Offer NEFT / RTGS wire instructions to customer finance team.",
      score: 65,
      expectedValue: 78000,
      evidence: [{ id: "e1", text: "High value corporate account", isPositive: true }],
    },
    policyDecision: {
      type: "HUMAN",
      decisionLabel: "HUMAN APPROVAL REQUIRED",
      reason: "High transaction amount (₹1.2L) and credit limit block.",
      explanation: "Requires sales account manager outreach.",
      rules: [{ id: "r1", text: "Exceeds ₹50k threshold", passed: false }],
    },
    status: "HUMAN_APPROVAL",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 07:45:00",
    updatedAt: "2026-08-28 07:46:00",
    auditTimeline: [
      { id: "a1", timestamp: "07:45", title: "Limit Exceeded", description: "Card declined due to credit limit.", category: "SYSTEM" },
      { id: "a2", timestamp: "07:46", title: "Escalated", description: "Sent to approval queue.", category: "POLICY", badgeText: "HUMAN APPROVAL REQUIRED" },
    ],
  },
  {
    id: "CASE-1120",
    customerName: "Zenith Software",
    customerEmail: "billing@zenithsw.io",
    problem: "Ambiguous double webhook callback",
    amount: 45000,
    score: 60,
    risk: "HIGH",
    type: "FAILED_PAYMENT",
    paymentState: "AMBIGUOUS",
    possibleDebit: true,
    retryCount: 0,
    maxRetries: 0,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Conflicting status codes returned by payment gateway.",
      recommendation: "DO NOT RETRY. Verify against bank portal first.",
      score: 60,
      expectedValue: 0,
      evidence: [{ id: "e1", text: "Duplicate webhook with payload mismatch", isPositive: false }],
    },
    policyDecision: {
      type: "BLOCK",
      decisionLabel: "BLOCKED — AMBIGUOUS PAYMENT",
      reason: "Conflicting signals; duplicate debit risk.",
      explanation: "Blocked until manual reconciliation.",
      rules: [{ id: "r1", text: "Ambiguity check failed", passed: false }],
    },
    status: "BLOCKED",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 06:30:00",
    updatedAt: "2026-08-28 06:31:00",
    auditTimeline: [
      { id: "a1", timestamp: "06:30", title: "Conflicting Signals", description: "Received SUCCESS and FAILED webhooks simultaneously.", category: "SYSTEM" },
      { id: "a2", timestamp: "06:31", title: "Hard Blocked", description: "Retry disabled by policy.", category: "POLICY", badgeText: "BLOCKED" },
    ],
  },
  {
    id: "CASE-1125",
    customerName: "Kiran & Sons",
    customerEmail: "kiran@kiransons.com",
    problem: "Bank server maintenance window",
    amount: 18500,
    score: 93,
    risk: "LOW",
    type: "FAILED_PAYMENT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "HDFC Bank core banking system maintenance (2 AM to 4 AM).",
      recommendation: "Retry at 05:00 AM after maintenance window completes.",
      score: 93,
      expectedValue: 17205,
      evidence: [
        { id: "e1", text: "Known scheduled maintenance code", isPositive: true },
        { id: "e2", text: "Flawless payment history outside maintenance hours", isPositive: true },
      ],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Standard maintenance retry window.",
      explanation: "Approved for execution after bank maintenance finishes.",
      rules: [{ id: "r1", text: "Clear failure reason", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 180,
    createdAt: "2026-08-28 02:15:00",
    updatedAt: "2026-08-28 02:16:00",
    auditTimeline: [
      { id: "a1", timestamp: "02:15", title: "Maintenance Failure", description: "Bank system unavailable error code.", category: "SYSTEM" },
      { id: "a2", timestamp: "02:16", title: "Postponed Retry", description: "Scheduled for 05:00 AM.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1130",
    customerName: "Omni Media House",
    customerEmail: "finance@omnimedia.in",
    problem: "International card 3DS challenge failure",
    amount: 62000,
    score: 75,
    risk: "MEDIUM",
    type: "CHECKOUT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 1,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "International OTP verification timed out.",
      recommendation: "Request alternative local payment method via email link.",
      score: 75,
      expectedValue: 46500,
      evidence: [{ id: "e1", text: "Cross-border payment flag", isPositive: false }],
    },
    policyDecision: {
      type: "HUMAN",
      decisionLabel: "HUMAN APPROVAL REQUIRED",
      reason: "High transaction value cross-border order.",
      explanation: "Requires risk officer review.",
      rules: [{ id: "r1", text: "Amount exceeds ₹50k auto limit", passed: false }],
    },
    status: "HUMAN_APPROVAL",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 05:40:00",
    updatedAt: "2026-08-28 05:41:00",
    auditTimeline: [
      { id: "a1", timestamp: "05:40", title: "3DS Failed", description: "OTP timeout on international card.", category: "SYSTEM" },
      { id: "a2", timestamp: "05:41", title: "Sent to Approvals Queue", description: "Awaiting risk team review.", category: "POLICY", badgeText: "HUMAN APPROVAL REQUIRED" },
    ],
  },
  {
    id: "CASE-1135",
    customerName: "ProHealth Clinic",
    customerEmail: "billing@prohealth.org",
    problem: "Recurring auto-debit revoked",
    amount: 12500,
    score: 86,
    risk: "LOW",
    type: "SUBSCRIPTION",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Customer e-mandate expired after 12 months.",
      recommendation: "Send e-mandate re-registration link via SMS.",
      score: 86,
      expectedValue: 10750,
      evidence: [{ id: "e1", text: "e-mandate mandate tenure completed", isPositive: true }],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Standard mandate renewal routine.",
      explanation: "Authorized automatic mandate renewal invitation.",
      rules: [{ id: "r1", text: "Compliance rules satisfied", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 15,
    createdAt: "2026-08-28 08:00:00",
    updatedAt: "2026-08-28 08:01:00",
    auditTimeline: [
      { id: "a1", timestamp: "08:00", title: "Mandate Expired", description: "E-mandate term elapsed.", category: "SYSTEM" },
      { id: "a2", timestamp: "08:01", title: "Renewal Sent", description: "Re-registration link generated.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1140",
    customerName: "Nimbus Cloud Tech",
    customerEmail: "accounts@nimbuscloud.in",
    problem: "Incorrect OTP entered twice",
    amount: 9800,
    score: 88,
    risk: "LOW",
    type: "CHECKOUT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "User mistyped OTP code twice in quick succession.",
      recommendation: "Send 1-click checkout recovery link to registered email.",
      score: 88,
      expectedValue: 8624,
      evidence: [{ id: "e1", text: "User active on checkout page", isPositive: true }],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Low risk OTP correction flow.",
      explanation: "Recovery link dispatched automatically.",
      rules: [{ id: "r1", text: "Amount within limit", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 2,
    createdAt: "2026-08-28 10:00:00",
    updatedAt: "2026-08-28 10:01:00",
    auditTimeline: [
      { id: "a1", timestamp: "10:00", title: "OTP Error", description: "Authentication failed twice.", category: "SYSTEM" },
      { id: "a2", timestamp: "10:01", title: "Link Sent", description: "1-click recovery email sent.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1145",
    customerName: "Starlight Hospitality",
    customerEmail: "gm@starlighthotels.in",
    problem: "Suspected stolen card alert",
    amount: 95000,
    score: 40,
    risk: "HIGH",
    type: "CHECKOUT",
    paymentState: "AMBIGUOUS",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 0,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "High fraud velocity score on card BIN.",
      recommendation: "DO NOT RETRY. Block transaction and alert fraud team.",
      score: 40,
      expectedValue: 0,
      evidence: [{ id: "e1", text: "Multiple IP changes during checkout", isPositive: false }],
    },
    policyDecision: {
      type: "BLOCK",
      decisionLabel: "BLOCKED — HIGH RISK FRAUD SIGNAL",
      reason: "Policy violation: High fraud risk indicator.",
      explanation: "Hard blocked to protect merchant chargeback ratio.",
      rules: [{ id: "r1", text: "Fraud filter triggered", passed: false }],
    },
    status: "BLOCKED",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 04:12:00",
    updatedAt: "2026-08-28 04:13:00",
    auditTimeline: [
      { id: "a1", timestamp: "04:12", title: "High Fraud Signal", description: "Flagged by fraud engine.", category: "SYSTEM" },
      { id: "a2", timestamp: "04:13", title: "Hard Blocked", description: "Transaction blocked permanently.", category: "POLICY", badgeText: "BLOCKED" },
    ],
  },
  {
    id: "CASE-1150",
    customerName: "Astra Logistics",
    customerEmail: "fleet@astralogistics.com",
    problem: "Card network routing error",
    amount: 28000,
    score: 90,
    risk: "LOW",
    type: "FAILED_PAYMENT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Primary payment gateway route degraded; backup gateway active.",
      recommendation: "Reroute transaction via secondary acquirer (ICICI Bank).",
      score: 90,
      expectedValue: 25200,
      evidence: [{ id: "e1", text: "Backup gateway health index 99.8%", isPositive: true }],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Smart routing failover approved.",
      explanation: "Rerouting executed automatically.",
      rules: [{ id: "r1", text: "Amount within limit", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 10,
    createdAt: "2026-08-28 09:30:00",
    updatedAt: "2026-08-28 09:31:00",
    auditTimeline: [
      { id: "a1", timestamp: "09:30", title: "Routing Degraded", description: "Primary gateway latency > 5s.", category: "SYSTEM" },
      { id: "a2", timestamp: "09:31", title: "Reroute Scheduled", description: "Backup acquirer selected.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1155",
    customerName: "Infinia FinTech",
    customerEmail: "treasury@infinia.in",
    problem: "Corporate net-banking authorization pending",
    amount: 150000,
    score: 80,
    risk: "MEDIUM",
    type: "INVOICE",
    paymentState: "BANK_TIMEOUT",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 1,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Awaiting secondary checker approval on corporate banking portal.",
      recommendation: "Extend authorization timeout window by 4 hours.",
      score: 80,
      expectedValue: 120000,
      evidence: [{ id: "e1", text: "Maker approval verified; checker pending", isPositive: true }],
    },
    policyDecision: {
      type: "HUMAN",
      decisionLabel: "HUMAN APPROVAL REQUIRED",
      reason: "High value corporate invoice (₹1.5L).",
      explanation: "Escalated for merchant CFO approval.",
      rules: [{ id: "r1", text: "Exceeds auto threshold", passed: false }],
    },
    status: "HUMAN_APPROVAL",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 03:00:00",
    updatedAt: "2026-08-28 03:02:00",
    auditTimeline: [
      { id: "a1", timestamp: "03:00", title: "Checker Pending", description: "Corporate portal checker pending.", category: "SYSTEM" },
      { id: "a2", timestamp: "03:02", title: "Escalated to CFO", description: "Placed in human approval queue.", category: "POLICY", badgeText: "HUMAN APPROVAL REQUIRED" },
    ],
  },
  {
    id: "CASE-1160",
    customerName: "Pinnacle EdTech",
    customerEmail: "support@pinnacleed.in",
    problem: "Course subscription renewal drop",
    amount: 4999,
    score: 94,
    risk: "LOW",
    type: "SUBSCRIPTION",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 2,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Insufficient funds on debit card.",
      recommendation: "Retry in 48 hours following month-end salary credit pattern.",
      score: 94,
      expectedValue: 4699,
      evidence: [{ id: "e1", text: "High student course completion rate", isPositive: true }],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Standard subscription retry schedule.",
      explanation: "Auto-retry authorized.",
      rules: [{ id: "r1", text: "Compliant low risk", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 2880,
    createdAt: "2026-08-28 01:20:00",
    updatedAt: "2026-08-28 01:21:00",
    auditTimeline: [
      { id: "a1", timestamp: "01:20", title: "Renewal Failed", description: "Card debit failed.", category: "SYSTEM" },
      { id: "a2", timestamp: "01:21", title: "Retry Queued", description: "Scheduled after 48h.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1165",
    customerName: "Matrix Engineering",
    customerEmail: "procurement@matrixeng.com",
    problem: "Vendor account mismatch",
    amount: 88000,
    score: 72,
    risk: "MEDIUM",
    type: "INVOICE",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 0,
    maxRetries: 1,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "GST number mismatch on invoice payment link.",
      recommendation: "Re-issue corrected invoice link with updated GST ID.",
      score: 72,
      expectedValue: 63360,
      evidence: [{ id: "e1", text: "Customer requested GST correction", isPositive: true }],
    },
    policyDecision: {
      type: "HUMAN",
      decisionLabel: "HUMAN APPROVAL REQUIRED",
      reason: "Invoice amendment requires approval.",
      explanation: "Requires billing admin approval.",
      rules: [{ id: "r1", text: "Invoice modification check", passed: false }],
    },
    status: "HUMAN_APPROVAL",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 06:10:00",
    updatedAt: "2026-08-28 06:11:00",
    auditTimeline: [
      { id: "a1", timestamp: "06:10", title: "GST Mismatch", description: "Payment link rejected due to tax ID mismatch.", category: "SYSTEM" },
      { id: "a2", timestamp: "06:11", title: "Approval Requested", description: "Escalated to billing manager.", category: "POLICY", badgeText: "HUMAN APPROVAL REQUIRED" },
    ],
  },
  {
    id: "CASE-1170",
    customerName: "Veritas Cyber Security",
    customerEmail: "billing@veritascyber.io",
    problem: "Annual license payment timeout",
    amount: 32000,
    score: 87,
    risk: "LOW",
    type: "FAILED_PAYMENT",
    paymentState: "CLEARLY_FAILED",
    possibleDebit: false,
    retryCount: 1,
    maxRetries: 3,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Transient network reset on payment gateway.",
      recommendation: "Retry immediately using fallback payment rail.",
      score: 87,
      expectedValue: 27840,
      evidence: [{ id: "e1", text: "Strong customer reputation score", isPositive: true }],
    },
    policyDecision: {
      type: "AUTO",
      decisionLabel: "AUTO-ALLOWED",
      reason: "Low risk transient retry.",
      explanation: "Fallback execution authorized.",
      rules: [{ id: "r1", text: "Amount within limit", passed: true }],
    },
    status: "SCHEDULED",
    scheduledDelayMinutes: 15,
    createdAt: "2026-08-28 09:10:00",
    updatedAt: "2026-08-28 09:11:00",
    auditTimeline: [
      { id: "a1", timestamp: "09:10", title: "Gateway Reset", description: "Connection reset during settlement.", category: "SYSTEM" },
      { id: "a2", timestamp: "09:11", title: "Fallback Retry Scheduled", description: "Retrying in 15 minutes.", category: "ACTION" },
    ],
  },
  {
    id: "CASE-1175",
    customerName: "Zenith Cloud Infra",
    customerEmail: "pay@zenithcloud.com",
    problem: "Duplicate request token detected",
    amount: 19500,
    score: 68,
    risk: "HIGH",
    type: "CHECKOUT",
    paymentState: "AMBIGUOUS",
    possibleDebit: true,
    retryCount: 0,
    maxRetries: 0,
    aiRecommendation: {
      badgeText: "AI Recommendation",
      diagnosis: "Idempotency key collision from double click on checkout.",
      recommendation: "DO NOT RETRY. Verify single charge processing state.",
      score: 68,
      expectedValue: 0,
      evidence: [{ id: "e1", text: "Identical idempotency token within 500ms", isPositive: false }],
    },
    policyDecision: {
      type: "BLOCK",
      decisionLabel: "BLOCKED — IDEMPOTENCY SAFETY GUARD",
      reason: "Potential duplicate execution blocked.",
      explanation: "Blocked by safety guardrail to prevent duplicate billing.",
      rules: [{ id: "r1", text: "Idempotency validation failed", passed: false }],
    },
    status: "BLOCKED",
    scheduledDelayMinutes: 0,
    createdAt: "2026-08-28 08:45:00",
    updatedAt: "2026-08-28 08:46:00",
    auditTimeline: [
      { id: "a1", timestamp: "08:45", title: "Idempotency Key Collision", description: "Dual click payload detected.", category: "SYSTEM" },
      { id: "a2", timestamp: "08:46", title: "Blocked by Guardrail", description: "Prevented duplicate payment trigger.", category: "POLICY", badgeText: "BLOCKED" },
    ],
  },
];
